services:
  mongodb:
    container_name: mongodb
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_ROOT_USERNAME: root
    networks:
      - dev-puzzle-net
  redis:
    container_name: redis
    restart: always
    image: 'redis'
    ports:
      - '6379:6379'
    networks:
      - dev-puzzle-net
volumes:
  mongo-data:

networks:
  dev-puzzle-net:
    name: dev-puzzle-net
    external: true