logging:
  level:
    '[org.springframework.web.client.RestClient]': TRACE

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

oauth:
  kakao:
    client-id: ${OAUTH-KAKAO-CLIENT-ID}
    client-secret: ${OAUTH-KAKAO-CLIENT-SECRET}
    redirect-url: http://localhost:8080/auth/oauth2/kakao/code
    oauth-endpoint-uri: https://kauth.kakao.com/oauth/authorize
    oauth-token-issue-uri: https://kauth.kakao.com/oauth/token
    oauth-userinfo-uri: https://kapi.kakao.com/v2/user/me
    oauth-unlink-uri: https://kapi.kakao.com/v1/user/unlink
    response-type: code
  google:
    client-id: ${OAUTH-GOOGLE-CLIENT-ID}
    client-secret: ${OAUTH-GOOGLE-CLIENT-SECRET}
    redirect-url: http://localhost:8080/auth/oauth2/google/code
    oauth-endpoint-uri: https://accounts.google.com/o/oauth2/v2/auth
    oauth-token-issue-uri: https://oauth2.googleapis.com/token
    oauth-userinfo-uri: https://www.googleapis.com/auth/userinfo.email
    oauth-unlink-uri: https://oauth2.googleapis.com/revoke
    scope: [ https://www.googleapis.com/auth/userinfo.email ]
    response-type: code

aws:
  s3:
    bucket-name: ${S3-BUCKET-NAME}
    retrieve-url: ${IMAGE-API}

cloud:
  aws:
    credentials:
      access-key: ${AWS-ACCESS-KEY}
      secret-key: ${AWS-SECRET-KEY}
    region:
      static: ${AWS-REGION}

jwt.secret: ${JWT-SECRET}
jwt.access-time-sec: 36003600
jwt.refresh-time-sec: 8640086400