logging:
  level:
    '[org.springframework.web.client.RestClient]': TRACE
    org:
      mongodb.driver: debug
  # 응답 값이 snake_case 로 하기 위함.
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    redis:
      host: ${REDIS_HOST}
      port: 63790 # Redis 서버 포트

oauth:
  kakao:
    client-id: ${OAUTH-KAKAO-CLIENT-ID}
    client-secret: ${OAUTH-KAKAO-CLIENT-SECRET}
    redirect-url: http://localhost:8080/auth/oauth2/kakao/code
    oauth-endpoint-uri: https://kauth.kakao.com/oauth/authorize
    oauth-token-issue-uri: https://kauth.kakao.com/oauth/token
    oauth-userinfo-uri: https://kapi.kakao.com/v2/user/me
    oauth-unlink-uri: https://kapi.kakao.com/v1/user/unlink
    response-type: code
  google:
    client-id: ${OAUTH-GOOGLE-CLIENT-ID}
    client-secret: ${OAUTH-GOOGLE-CLIENT-SECRET}
    redirect-url: http://localhost:8080/auth/oauth2/google/code
    oauth-endpoint-uri: https://accounts.google.com/o/oauth2/v2/auth
    oauth-token-issue-uri: https://oauth2.googleapis.com/token
    oauth-userinfo-uri: https://www.googleapis.com/auth/userinfo.email
    oauth-unlink-uri: https://oauth2.googleapis.com/revoke
    scope: [ https://www.googleapis.com/auth/userinfo.email ]
    response-type: code

jwt.secret: ${JWT-SECRET}
jwt.access-time-sec: 3600
jwt.refresh-time-sec: 86400