logging:
  level:
    '[org.springframework.web.client.RestClient]': TRACE

spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only

  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/${MONGO_INITDB_DATABASE}
    redis:
      host: localhost
      port: 6379 # Redis 서버 포트

oauth:
  kakao:
    client-id: ${OAUTH-KAKAO-CLIENT-ID}
    client-secret: ${OAUTH-KAKAO-CLIENT-SECRET}
    oauth-endpoint-uri: https://kauth.kakao.com/oauth/authorize
    oauth-token-issue-uri: https://kauth.kakao.com/oauth/token
    oauth-userinfo-uri: https://kapi.kakao.com/v2/user/me
    oauth-unlink-uri: https://kapi.kakao.com/v1/user/unlink
    response-type: code
  google:
    client-id: ${OAUTH-GOOGLE-CLIENT-ID}
    client-secret: ${OAUTH-GOOGLE-CLIENT-SECRET}
    oauth-endpoint-uri: https://accounts.google.com/o/oauth2/v2/auth
    oauth-token-issue-uri: https://oauth2.googleapis.com/token
    oauth-userinfo-uri: https://www.googleapis.com/auth/userinfo.email
    oauth-unlink-uri: https://oauth2.googleapis.com/revoke
    scope: [ https://www.googleapis.com/auth/userinfo.email ]
    response-type: code

aws:
  s3:
    bucket-name: nyangpuzzle
    retrieve-url: ${IMAGE-API}

cloud:
  aws:
    credentials:
      access-key: ${AWS-ACCESS-KEY}
      secret-key: ${AWS-SECRET-KEY}
    region:
      static: ${AWS-REGION}


jwt.secret: jwt-secret
jwt.access-time-sec: 360036003600
jwt.refresh-time-sec: 864008640086400