name: Deploy to Develop

on:
  push:
    branches:
      - develop

jobs:
  develop-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/404158275662/locations/global/workloadIdentityPools/my-pool/providers/nyangdevops
          service_account: minshiknyang@nyang-453314.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v1
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'asia-northeast3-docker.pkg.dev'

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Tag Docker image Build and Push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: asia-northeast3-docker.pkg.dev/nyang-453314/nyangpuzzle/dev/backend-api:latest, asia-northeast3-docker.pkg.dev/nyang-453314/nyangpuzzle/dev/backend-api:${{ steps.get-tag.outputs.short_ref }}

      - name: Deploy to Development Environment
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script: |
            cd project/puzzle/
            sh dev_run.sh